// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartRepository.Persistence;

namespace SmartWebAPI.Migrations
{
    [DbContext(typeof(PlutoContext))]
    [Migration("20220326025615_Added_Location_Libraries")]
    partial class Added_Location_Libraries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartRepository.Core.Models.User", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("deleted_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deleted_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("hash_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartRepository.Core.Models.lib_barangay", b =>
                {
                    b.Property<string>("barangayCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("barangayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("islandGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("provinceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regionCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("barangayCode");

                    b.ToTable("Lib_Barangays");
                });

            modelBuilder.Entity("SmartRepository.Core.Models.lib_city", b =>
                {
                    b.Property<string>("cityCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isCapital")
                        .HasColumnType("bit");

                    b.Property<string>("islandGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("provinceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regionCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cityCode");

                    b.ToTable("Lib_Cities");
                });

            modelBuilder.Entity("SmartRepository.Core.Models.lib_province", b =>
                {
                    b.Property<string>("provinceCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("islandGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("provinceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regionCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("provinceCode");

                    b.ToTable("Lib_Provinces");
                });

            modelBuilder.Entity("SmartRepository.Core.Models.lib_region", b =>
                {
                    b.Property<string>("regionCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("islandGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("regionCode");

                    b.ToTable("Lib_Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
